//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeniceTideCommon.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VeniceTideCommon.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data on tide phases and heights are based on values from the City of Venice web site (www.comune.venezia.it)..
        /// </summary>
        public static string AboutPageBasedOn {
            get {
                return ResourceManager.GetString("AboutPageBasedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is strictly for rough guidance and should never be relied upon in critical situations..
        /// </summary>
        public static string AboutPageGuidance {
            get {
                return ResourceManager.GetString("AboutPageGuidance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app uses your phone&apos;s internet connection to retrieve tide data which might be taxed by your subscription provider..
        /// </summary>
        public static string AboutPageInet {
            get {
                return ResourceManager.GetString("AboutPageInet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venice Tide by LionFisk, 2013. Feedback very much appreciated at contact@lionfisk.com. Unfortunately we cannot reply to reviews on the Store..
        /// </summary>
        public static string AboutPageLead {
            get {
                return ResourceManager.GetString("AboutPageLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tide height values are predictions and calculations. LionFisk provides no guarantee as to the accuracies of these predictions and calculations..
        /// </summary>
        public static string AboutPageNoGuarantee {
            get {
                return ResourceManager.GetString("AboutPageNoGuarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations provided by Lavinia Sella..
        /// </summary>
        public static string AboutPageTranslations {
            get {
                return ResourceManager.GetString("AboutPageTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AppBarAbout {
            get {
                return ResourceManager.GetString("AppBarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live tile.
        /// </summary>
        public static string AppBarLiveTile {
            get {
                return ResourceManager.GetString("AppBarLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locations.
        /// </summary>
        public static string AppBarLocations {
            get {
                return ResourceManager.GetString("AppBarLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venice Tide.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that you have disabled the Background Task that allows Venice Tide to automatically update the live tile. Please reenable this in Settings, Applications, Background Tasks before adding the live tile..
        /// </summary>
        public static string BackgroundAgentDisabledErrorMsg {
            get {
                return ResourceManager.GetString("BackgroundAgentDisabledErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your locations.
        /// </summary>
        public static string CurrentFavLocsTitle {
            get {
                return ResourceManager.GetString("CurrentFavLocsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (calculated from predictions).
        /// </summary>
        public static string CurrentTideLevelNote {
            get {
                return ResourceManager.GetString("CurrentTideLevelNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tide level.
        /// </summary>
        public static string CurrentTideLevelTitle {
            get {
                return ResourceManager.GetString("CurrentTideLevelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit locations.
        /// </summary>
        public static string EditFavsPageTitle {
            get {
                return ResourceManager.GetString("EditFavsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        public static string ForecastHighTideTimeLead {
            get {
                return ResourceManager.GetString("ForecastHighTideTimeLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  at .
        /// </summary>
        public static string ForecastLowTideTimeLead {
            get {
                return ResourceManager.GetString("ForecastLowTideTimeLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low tide: .
        /// </summary>
        public static string ForecastLowTideTitle {
            get {
                return ResourceManager.GetString("ForecastLowTideTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        public static string ListSeparatorWithSpace {
            get {
                return ResourceManager.GetString("ListSeparatorWithSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently.
        /// </summary>
        public static string LiveTileCurrentlyTitle {
            get {
                return ResourceManager.GetString("LiveTileCurrentlyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that Venice Tide has not yet been able to download updated tide data from the internet. Please be aware that the live tile will not be accurate until fresh data has been downloaded..
        /// </summary>
        public static string LiveTileDataNotFresh {
            get {
                return ResourceManager.GetString("LiveTileDataNotFresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast.
        /// </summary>
        public static string LiveTileForecastTitle {
            get {
                return ResourceManager.GetString("LiveTileForecastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add live tile.
        /// </summary>
        public static string LiveTilePageAddBtn {
            get {
                return ResourceManager.GetString("LiveTilePageAddBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a live tile from Venice Tide to your start screen you will be able to know about the level of the coming high tides. It will also show the flooding status of your favorite locations. Please note that the live tile cannot update more often than once every 30 minutes due to Windows Phone restrictions..
        /// </summary>
        public static string LiveTilePageExplanation {
            get {
                return ResourceManager.GetString("LiveTilePageExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Tile.
        /// </summary>
        public static string LiveTilePageTitle {
            get {
                return ResourceManager.GetString("LiveTilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and {0}cm above current tide level..
        /// </summary>
        public static string LocHeightDescAbove {
            get {
                return ResourceManager.GetString("LocHeightDescAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and is currently flooded by {0}cm..
        /// </summary>
        public static string LocHeightDescFlooded {
            get {
                return ResourceManager.GetString("LocHeightDescFlooded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is {0}cm above mean sea level.
        /// </summary>
        public static string LocHeightDescLead {
            get {
                return ResourceManager.GetString("LocHeightDescLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to but only {0}cm above current tide level..
        /// </summary>
        public static string LocHeightDescSlightlyAbove {
            get {
                return ResourceManager.GetString("LocHeightDescSlightlyAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and {0}cm below current tide level..
        /// </summary>
        public static string LocHeightDescSlightlyUnder {
            get {
                return ResourceManager.GetString("LocHeightDescSlightlyUnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}cm above mean sea level..
        /// </summary>
        public static string LocHeightText {
            get {
                return ResourceManager.GetString("LocHeightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently.
        /// </summary>
        public static string MainPivotCurrentlyTitle {
            get {
                return ResourceManager.GetString("MainPivotCurrentlyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast.
        /// </summary>
        public static string MainPivotForecastTitle {
            get {
                return ResourceManager.GetString("MainPivotForecastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing....
        /// </summary>
        public static string ProgressBarRefreshingData {
            get {
                return ResourceManager.GetString("ProgressBarRefreshingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flooded locations: {0}..
        /// </summary>
        public static string TideDPFloodedLocs {
            get {
                return ResourceManager.GetString("TideDPFloodedLocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of your locations will likely be flooded..
        /// </summary>
        public static string TideDPNoFloodedLocs {
            get {
                return ResourceManager.GetString("TideDPNoFloodedLocs", resourceCulture);
            }
        }
    }
}
